version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - mysql_node_network
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_USER: user 
      MYSQL_PASSWORD: azerty
      MYSQL_DATABASE: forumdb
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - ./back-end/db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./back-end/data:/var/lib/mysql
  
  nodeapp:
    container_name: nodeapp_c
    build: ./back-end
    image: nodeapp
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/usr/code
      - /usr/code/node_modules
      - ./back-end/uploads:/usr/code/uploads
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: 'user'
      DB_PASSWORD: 'azerty'
      DB_NAME: forumdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeapp
    depends_on:
      - mysql
    networks:
      - mysql_node_network
  
  reactapp:
    container_name: reactapp_c
    build: ./front-end
    image: reactapp
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - nodeapp
    networks:
      - mysql_node_network

networks:
  mysql_node_network:
